#ifndef MACROSOVERLOADED_H_INCLUDED
#define MACROSOVERLOADED_H_INCLUDED


#define MACROSOVERLOADED_CAT_1_(A, B) A ## B
#define MACROSOVERLOADED_CAT_2_(A, B) MACROSOVERLOADED_CAT_1_(A, B)

#define MACROSOVERLOADED_ARGS_COUNT_HELP_(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, COUNT, ...) COUNT
#define MACROSOVERLOADED_ARGS_COUNT_(...)\
    MACROSOVERLOADED_ARGS_COUNT_HELP_(__VA_ARGS__, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1)

#define SELECT_OVERLOADED_MACROS(NAME, ...)\
MACROSOVERLOADED_CAT_2_(NAME, MACROSOVERLOADED_ARGS_COUNT_(__VA_ARGS__))(__VA_ARGS__)


#endif
